version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.8.4-openjdk-17

    steps:
      - checkout
      - run:
          name: Build Spring Boot application
          command: |
            sudo apt-get update && sudo apt-get install docker-ce
            mvn package -DskipTests

      - run:
          name: Build Docker image
          command: |
            docker build -t tnm-training .
            docker login -u dwijptltnm -p Technman@I2024!!  # Adjust credentials if needed
            docker tag tnm-training dwijptltnm/tnm-training
            docker push dwijptltnm/tnm-training

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
